import numpy as np
import pandas as pd

from src.dynamics.orbit import (
    R_EARTH
)

from src.dynamics.orbital_elements import (
    keplerian_to_cartesian
)

from src.dynamics.non_gravitational_forces import (
    propagate_orbit_with_j2_and_drag_like
)

from src.navigation.gnss_ekf_interface import (
    generate_simplified_gps_positions,
    select_visible_gnss_satellites
)

from src.navigation.gnss_signal_propagation import (
    simulate_pseudoranges_with_transmit_time,
    compute_transmit_time_solution_covariance
)

from src.navigation.gnss_fdir_transmit_time import (
    solve_gnss_with_fdir_transmit_time
)

from src.ai.gnss_anomaly_features import (
    extract_gnss_anomaly_features
)

from src.ai.gnss_temporal_features import (
    add_causal_temporal_features,
    temporal_feature_valid_mask
)

from src.ai.hybrid_anomaly_supervisor import (
    HybridGnssAnomalySupervisor
)


# ============================================================
# AURORA
# Phase 16-C
#
# Frozen AI / FDIR robustness evaluation
#
#
# Purpose:
#
# Evaluate the Phase-15 temporal anomaly detector WITHOUT:
#
#   - retraining
#   - recalibration
#   - threshold adaptation
#
# under the varying GNSS/fault conditions generated by
# the validated Phase-16 Latin-Hypercube campaign.
#
#
# Two paired sequences are created for every scenario:
#
#       NOMINAL
#       FAULT
#
# They share:
#
#       same orbit
#       same geometry
#       same pseudorange noise
#       same prior
#
# The only difference is fault injection.
#
#
# AI prior model:
#
# Phase 16-C keeps the Phase-15 navigation-prior model:
#
#       position prior error ~ N(0, 20 m)
#       clock prior error ~ N(0, 10 m)
#
# This phase therefore tests robustness to:
#
#       pseudorange noise
#       fault magnitude
#       fault timing
#       fault duration
#       small truth-trajectory changes caused by a_ng
#
# Full navigation-state uncertainty was tested in 016-B.
# ============================================================


# ------------------------------------------------------------
# 1. CONSTANTS
# ------------------------------------------------------------

DT = (
    10.0
)


SIMULATION_END_MIN = (
    122.0
)


SEQUENCE_START_MIN = (
    98.0
)


SEQUENCE_END_MIN = (
    122.0
)


RECEIVER_CLOCK_BIAS_SECONDS = (
    100.0e-6
)


SPEED_OF_LIGHT = (
    299_792_458.0
)


TRUE_CLOCK_BIAS_METERS = (
    SPEED_OF_LIGHT
    *
    RECEIVER_CLOCK_BIAS_SECONDS
)


GNSS_CONFIDENCE = (
    0.99
)


PREFERRED_FAULT_SATELLITE = (
    "GPS04"
)


PRIOR_POSITION_SIGMA_M = (
    20.0
)


PRIOR_CLOCK_SIGMA_M = (
    10.0
)


AI_VOTE_WINDOW = (
    3
)


MINIMUM_AI_VOTES = (
    2
)


# ------------------------------------------------------------
# 2. ORBIT
# ------------------------------------------------------------

SEMI_MAJOR_AXIS = (
    R_EARTH
    +
    550_000.0
)


ECCENTRICITY = (
    0.01
)


INCLINATION = np.deg2rad(
    97.6
)


RAAN = np.deg2rad(
    40.0
)


ARGUMENT_OF_PERIAPSIS = np.deg2rad(
    30.0
)


TRUE_ANOMALY = np.deg2rad(
    25.0
)


# ------------------------------------------------------------
# 3. HELPERS
# ------------------------------------------------------------

def _percentage(
    values
):

    values = np.asarray(
        values,
        dtype=bool
    )


    if values.size == 0:

        return np.nan


    return float(
        100.0
        *
        np.mean(
            values
        )
    )


def _select_five_satellites(
    visible_ids
):

    visible_ids = [
        str(
            satellite_id
        ).strip()
        for satellite_id in visible_ids
    ]


    if len(
        visible_ids
    ) < 5:

        return None


    if (
        PREFERRED_FAULT_SATELLITE
        in
        visible_ids
    ):

        other_ids = [
            satellite_id
            for satellite_id in visible_ids
            if satellite_id
            !=
            PREFERRED_FAULT_SATELLITE
        ]


        return (
            [
                PREFERRED_FAULT_SATELLITE
            ]
            +
            other_ids[
                :4
            ]
        )


    return (
        visible_ids[
            :5
        ]
    )


def _choose_fault_target(
    satellite_ids
):

    if (
        PREFERRED_FAULT_SATELLITE
        in
        satellite_ids
    ):

        return (
            PREFERRED_FAULT_SATELLITE
        )


    return (
        satellite_ids[
            0
        ]
    )


# ------------------------------------------------------------
# 4. TRUTH
# ------------------------------------------------------------

def _build_truth(
    base_acceleration
):

    simulation_duration_seconds = (
        SIMULATION_END_MIN
        *
        60.0
    )


    number_of_epochs = (
        int(
            simulation_duration_seconds
            /
            DT
        )
        +
        1
    )


    time = np.linspace(
        0.0,
        simulation_duration_seconds,
        number_of_epochs
    )


    time_minutes = (
        time
        /
        60.0
    )


    (
        initial_position,
        initial_velocity
    ) = keplerian_to_cartesian(
        SEMI_MAJOR_AXIS,
        ECCENTRICITY,
        INCLINATION,
        RAAN,
        ARGUMENT_OF_PERIAPSIS,
        TRUE_ANOMALY
    )


    initial_state = np.concatenate(
        (
            initial_position,
            initial_velocity
        )
    )


    solution = (
        propagate_orbit_with_j2_and_drag_like(
            initial_state=
                initial_state,

            duration=
                simulation_duration_seconds,

            number_of_points=
                number_of_epochs,

            base_acceleration=
                float(
                    base_acceleration
                )
        )
    )


    truth_states = (
        solution.y.T
    )


    synchronization_error = float(
        np.max(
            np.abs(
                solution.t
                -
                time
            )
        )
    )


    sequence_mask = (
        (
            time_minutes
            >=
            SEQUENCE_START_MIN
        )
        &
        (
            time_minutes
            <=
            SEQUENCE_END_MIN
        )
    )


    sequence_indices = np.where(
        sequence_mask
    )[0]


    return {
        "time":
            time,

        "time_minutes":
            time_minutes,

        "truth_states":
            truth_states,

        "sequence_indices":
            sequence_indices,

        "synchronization_error":
            synchronization_error
    }


# ------------------------------------------------------------
# 5. BUILD ONE FDIR FEATURE ROW
# ------------------------------------------------------------

def _build_fdir_feature_row(
    satellite_ids,
    pseudoranges,
    reception_time_seconds,
    prior_position,
    prior_clock_bias_meters,
    pseudorange_noise_std
):

    try:

        fdir_result = (
            solve_gnss_with_fdir_transmit_time(
                satellite_ids=
                    satellite_ids,

                pseudoranges=
                    pseudoranges,

                reception_time_seconds=
                    reception_time_seconds,

                initial_position=
                    prior_position,

                initial_clock_bias_meters=
                    prior_clock_bias_meters,

                pseudorange_noise_std=
                    pseudorange_noise_std,

                confidence=
                    GNSS_CONFIDENCE
            )
        )


    except (
        RuntimeError,
        ValueError,
        np.linalg.LinAlgError
    ):

        return None


    full_solution = (
        fdir_result.get(
            "full_solution",
            None
        )
    )


    if full_solution is None:

        full_solution = (
            fdir_result.get(
                "solution",
                None
            )
        )


    if (
        full_solution is None
        or
        not full_solution.get(
            "converged",
            False
        )
    ):

        return None


    try:

        covariance_result = (
            compute_transmit_time_solution_covariance(
                receiver_position=
                    full_solution[
                        "position"
                    ],

                satellite_ids=
                    satellite_ids,

                reception_time_seconds=
                    reception_time_seconds,

                pseudorange_noise_std=
                    pseudorange_noise_std
            )
        )


        pdop = float(
            covariance_result[
                "pdop"
            ]
        )


    except (
        RuntimeError,
        ValueError,
        np.linalg.LinAlgError,
        KeyError
    ):

        return None


    features = (
        extract_gnss_anomaly_features(
            fdir_result=
                fdir_result,

            number_of_satellites=
                len(
                    satellite_ids
                ),

            pseudorange_noise_std=
                pseudorange_noise_std,

            confidence=
                GNSS_CONFIDENCE,

            pdop=
                pdop,

            prior_position=
                prior_position,

            prior_clock_bias_meters=
                prior_clock_bias_meters
        )
    )


    if features is None:

        return None


    return {
        "fdir_detected":
            int(
                bool(
                    fdir_result.get(
                        "fault_detected",
                        False
                    )
                )
            ),

        "measurement_accepted":
            int(
                bool(
                    fdir_result.get(
                        "measurement_accepted",
                        False
                    )
                )
            ),

        **features
    }


# ------------------------------------------------------------
# 6. BUILD PAIRED NOMINAL / FAULT SEQUENCES
# ------------------------------------------------------------

def _generate_paired_sequences(
    scenario
):

    scenario = dict(
        scenario
    )


    truth = (
        _build_truth(
            base_acceleration=
                scenario[
                    "non_gravitational_acceleration_mps2"
                ]
        )
    )


    pseudorange_rng = np.random.default_rng(
        int(
            scenario[
                "scenario_seed"
            ]
        )
        +
        5101
    )


    prior_rng = np.random.default_rng(
        int(
            scenario[
                "scenario_seed"
            ]
        )
        +
        5202
    )


    # ========================================================
    # Keep Phase-15 prior model fixed.
    # ========================================================

    prior_position_error = (
        prior_rng.normal(
            0.0,
            PRIOR_POSITION_SIGMA_M,
            size=3
        )
    )


    prior_clock_error = float(
        prior_rng.normal(
            0.0,
            PRIOR_CLOCK_SIGMA_M
        )
    )


    pseudorange_noise_std = float(
        scenario[
            "pseudorange_noise_std_m"
        ]
    )


    fault_magnitude = float(
        scenario[
            "fault_magnitude_m"
        ]
    )


    fault_start_min = float(
        scenario[
            "fault_start_min"
        ]
    )


    fault_end_min = (
        fault_start_min
        +
        float(
            scenario[
                "fault_duration_min"
            ]
        )
    )


    rows = []


    failed_epochs = (
        0
    )


    expected_epoch_count = len(
        truth[
            "sequence_indices"
        ]
    )


    for epoch_index in truth[
        "sequence_indices"
    ]:

        reception_time_seconds = float(
            truth[
                "time"
            ][
                epoch_index
            ]
        )


        reception_time_minutes = float(
            truth[
                "time_minutes"
            ][
                epoch_index
            ]
        )


        true_receiver_position = (
            truth[
                "truth_states"
            ][
                epoch_index,
                0:3
            ]
        )


        prior_position = (
            true_receiver_position
            +
            prior_position_error
        )


        prior_clock_bias_meters = (
            TRUE_CLOCK_BIAS_METERS
            +
            prior_clock_error
        )


        # ====================================================
        # GNSS visibility
        # ====================================================

        (
            all_positions,
            all_ids
        ) = generate_simplified_gps_positions(
            time_seconds=
                reception_time_seconds
        )


        (
            _,
            visible_ids
        ) = select_visible_gnss_satellites(
            receiver_position=
                true_receiver_position,

            satellite_positions=
                all_positions,

            satellite_ids=
                all_ids
        )


        working_ids = (
            _select_five_satellites(
                visible_ids
            )
        )


        if working_ids is None:

            failed_epochs += (
                1
            )

            continue


        # ====================================================
        # ONE noise realization shared by paired conditions.
        # ====================================================

        nominal_measurement = (
            simulate_pseudoranges_with_transmit_time(
                receiver_position=
                    true_receiver_position,

                satellite_ids=
                    working_ids,

                reception_time_seconds=
                    reception_time_seconds,

                receiver_clock_bias_seconds=
                    RECEIVER_CLOCK_BIAS_SECONDS,

                pseudorange_noise_std=
                    pseudorange_noise_std,

                rng=
                    pseudorange_rng
            )
        )


        base_pseudoranges = np.asarray(
            nominal_measurement[
                "pseudoranges"
            ],
            dtype=float
        )


        fault_target = (
            _choose_fault_target(
                working_ids
            )
        )


        fault_target_index = (
            working_ids.index(
                fault_target
            )
        )


        fault_active = (
            reception_time_minutes
            >=
            fault_start_min
            and
            reception_time_minutes
            <
            fault_end_min
        )


        # ====================================================
        # NOMINAL + FAULT conditions
        # ====================================================

        epoch_success = (
            True
        )


        for condition in [
            "NOMINAL",
            "FAULT"
        ]:

            pseudoranges = (
                base_pseudoranges.copy()
            )


            injected_fault = (
                condition
                ==
                "FAULT"
                and
                fault_active
            )


            if injected_fault:

                pseudoranges[
                    fault_target_index
                ] += (
                    fault_magnitude
                )


            row = (
                _build_fdir_feature_row(
                    satellite_ids=
                        working_ids,

                    pseudoranges=
                        pseudoranges,

                    reception_time_seconds=
                        reception_time_seconds,

                    prior_position=
                        prior_position,

                    prior_clock_bias_meters=
                        prior_clock_bias_meters,

                    pseudorange_noise_std=
                        pseudorange_noise_std
                )
            )


            if row is None:

                epoch_success = (
                    False
                )

                break


            rows.append(
                {
                    "scenario_id":
                        str(
                            scenario[
                                "scenario_id"
                            ]
                        ),

                    "condition":
                        condition,

                    "epoch_index":
                        int(
                            epoch_index
                        ),

                    "time_seconds":
                        reception_time_seconds,

                    "time_minutes":
                        reception_time_minutes,

                    "fault_active":
                        int(
                            injected_fault
                        ),

                    "fault_magnitude_m":
                        fault_magnitude,

                    "pseudorange_noise_std_m":
                        pseudorange_noise_std,

                    **row
                }
            )


        if not epoch_success:

            # Remove a possible first paired row from this epoch.
            rows = [
                row
                for row in rows
                if row[
                    "epoch_index"
                ]
                !=
                int(
                    epoch_index
                )
            ]


            failed_epochs += (
                1
            )


    dataframe = pd.DataFrame(
        rows
    )


    if len(
        dataframe
    ) == 0:

        raise RuntimeError(
            "Empty Phase-16C scenario dataset."
        )


    expected_rows = (
        2
        *
        (
            expected_epoch_count
            -
            failed_epochs
        )
    )


    pairs_complete = (
        len(
            dataframe
        )
        ==
        expected_rows
    )


    return {
        "dataframe":
            dataframe,

        "failed_epochs":
            int(
                failed_epochs
            ),

        "expected_epoch_count":
            int(
                expected_epoch_count
            ),

        "pairs_complete":
            bool(
                pairs_complete
            ),

        "synchronization_error":
            float(
                truth[
                    "synchronization_error"
                ]
            ),

        "fault_start_min":
            fault_start_min,

        "fault_end_min":
            fault_end_min
    }


# ------------------------------------------------------------
# 7. ADD AI + SUPERVISOR
# ------------------------------------------------------------

def _run_frozen_detector(
    dataframe,
    detector
):

    dataframe = (
        add_causal_temporal_features(
            dataframe=
                dataframe,

            group_columns=[
                "scenario_id",
                "condition"
            ],

            time_column=
                "time_seconds"
        )
    )


    valid_mask = (
        temporal_feature_valid_mask(
            dataframe
        )
    )


    dataframe[
        "temporal_features_valid"
    ] = (
        valid_mask.astype(
            int
        )
    )


    valid_dataframe = dataframe[
        valid_mask
    ].copy()


    if len(
        valid_dataframe
    ) == 0:

        raise RuntimeError(
            "No valid temporal features in Phase 16-C scenario."
        )


    valid_dataframe = (
        valid_dataframe.sort_values(
            [
                "condition",
                "time_seconds"
            ]
        )
        .reset_index(
            drop=True
        )
    )


    valid_dataframe[
        "temporal_score"
    ] = (
        detector.score_samples(
            valid_dataframe
        )
    )


    valid_dataframe[
        "ai_raw_alarm"
    ] = (
        valid_dataframe[
            "temporal_score"
        ]
        >=
        detector.threshold
    ).astype(
        int
    )


    naive_or_alarm = np.zeros(
        len(
            valid_dataframe
        ),
        dtype=int
    )


    hybrid_alarm = np.zeros(
        len(
            valid_dataframe
        ),
        dtype=int
    )


    ai_confirmed = np.zeros(
        len(
            valid_dataframe
        ),
        dtype=int
    )


    for condition in [
        "NOMINAL",
        "FAULT"
    ]:

        indices = (
            valid_dataframe.index[
                valid_dataframe[
                    "condition"
                ]
                ==
                condition
            ]
            .tolist()
        )


        indices = sorted(
            indices,
            key=
                lambda index:
                    valid_dataframe.loc[
                        index,
                        "time_seconds"
                    ]
        )


        supervisor = (
            HybridGnssAnomalySupervisor(
                ai_vote_window=
                    AI_VOTE_WINDOW,

                minimum_ai_votes=
                    MINIMUM_AI_VOTES
            )
        )


        for index in indices:

            classical_alarm = bool(
                valid_dataframe.loc[
                    index,
                    "fdir_detected"
                ]
            )


            raw_ai_alarm = bool(
                valid_dataframe.loc[
                    index,
                    "ai_raw_alarm"
                ]
            )


            decision = (
                supervisor.update(
                    classical_alarm=
                        classical_alarm,

                    ai_raw_alarm=
                        raw_ai_alarm
                )
            )


            naive_or_alarm[
                index
            ] = int(
                classical_alarm
                or
                raw_ai_alarm
            )


            hybrid_alarm[
                index
            ] = int(
                decision.hard_alarm
            )


            ai_confirmed[
                index
            ] = int(
                decision.ai_confirmed
            )


    valid_dataframe[
        "naive_or_alarm"
    ] = (
        naive_or_alarm
    )


    valid_dataframe[
        "hybrid_alarm"
    ] = (
        hybrid_alarm
    )


    valid_dataframe[
        "ai_confirmed"
    ] = (
        ai_confirmed
    )


    return valid_dataframe


# ------------------------------------------------------------
# 8. ALARM EPISODES
# ------------------------------------------------------------

def _count_alarm_episodes(
    dataframe,
    alarm_column
):

    dataframe = dataframe.sort_values(
        "time_seconds"
    )


    alarms = dataframe[
        alarm_column
    ].to_numpy(
        dtype=int
    )


    episodes = (
        0
    )


    previous = (
        0
    )


    for alarm in alarms:

        if (
            alarm
            ==
            1
            and
            previous
            ==
            0
        ):

            episodes += (
                1
            )


        previous = (
            alarm
        )


    return int(
        episodes
    )


# ------------------------------------------------------------
# 9. NEW FAULT-EPISODE DETECTION
#
# We do not credit an alarm that was already active before
# fault onset as a new fault detection.
# ------------------------------------------------------------

def _fault_episode_diagnostics(
    dataframe,
    alarm_column,
    fault_start_min,
    fault_end_min
):

    dataframe = dataframe.sort_values(
        "time_seconds"
    ).reset_index(
        drop=True
    )


    times_minutes = dataframe[
        "time_minutes"
    ].to_numpy(
        dtype=float
    )


    alarms = dataframe[
        alarm_column
    ].to_numpy(
        dtype=int
    )


    fault_mask = (
        (
            times_minutes
            >=
            fault_start_min
        )
        &
        (
            times_minutes
            <
            fault_end_min
        )
    )


    fault_indices = np.where(
        fault_mask
    )[0]


    if len(
        fault_indices
    ) == 0:

        return {
            "episode_detected":
                False,

            "preexisting_alarm":
                False,

            "latency_s":
                np.nan
        }


    first_fault_index = (
        fault_indices[
            0
        ]
    )


    if first_fault_index > 0:

        previous_alarm = int(
            alarms[
                first_fault_index - 1
            ]
        )

    else:

        previous_alarm = (
            0
        )


    preexisting_alarm = (
        previous_alarm
        ==
        1
    )


    for index in fault_indices:

        current_alarm = int(
            alarms[
                index
            ]
        )


        if (
            current_alarm
            ==
            1
            and
            previous_alarm
            ==
            0
        ):

            latency_seconds = (
                (
                    times_minutes[
                        index
                    ]
                    -
                    fault_start_min
                )
                *
                60.0
            )


            return {
                "episode_detected":
                    True,

                "preexisting_alarm":
                    preexisting_alarm,

                "latency_s":
                    float(
                        max(
                            latency_seconds,
                            0.0
                        )
                    )
            }


        previous_alarm = (
            current_alarm
        )


    return {
        "episode_detected":
            False,

        "preexisting_alarm":
            preexisting_alarm,

        "latency_s":
            np.nan
    }


# ------------------------------------------------------------
# 10. MAIN SCENARIO RUNNER
# ------------------------------------------------------------

def run_ai_robustness_scenario(
    scenario,
    detector
):

    scenario = dict(
        scenario
    )


    generated = (
        _generate_paired_sequences(
            scenario
        )
    )


    dataframe = (
        _run_frozen_detector(
            dataframe=
                generated[
                    "dataframe"
                ],

            detector=
                detector
        )
    )


    nominal = dataframe[
        dataframe[
            "condition"
        ]
        ==
        "NOMINAL"
    ].copy()


    fault_sequence = dataframe[
        dataframe[
            "condition"
        ]
        ==
        "FAULT"
    ].copy()


    active_fault = fault_sequence[
        fault_sequence[
            "fault_active"
        ]
        ==
        1
    ].copy()


    if len(
        nominal
    ) == 0:

        raise RuntimeError(
            "No nominal evaluation samples in Phase 16-C."
        )


    if len(
        active_fault
    ) == 0:

        raise RuntimeError(
            "No active-fault samples in Phase 16-C."
        )


    # ========================================================
    # Nominal P_FA
    # ========================================================

    fdir_pfa = (
        _percentage(
            nominal[
                "fdir_detected"
            ].to_numpy(
                dtype=bool
            )
        )
    )


    ai_pfa = (
        _percentage(
            nominal[
                "ai_raw_alarm"
            ].to_numpy(
                dtype=bool
            )
        )
    )


    naive_or_pfa = (
        _percentage(
            nominal[
                "naive_or_alarm"
            ].to_numpy(
                dtype=bool
            )
        )
    )


    hybrid_pfa = (
        _percentage(
            nominal[
                "hybrid_alarm"
            ].to_numpy(
                dtype=bool
            )
        )
    )


    # ========================================================
    # Fault-window epoch detection
    # ========================================================

    fdir_pd = (
        _percentage(
            active_fault[
                "fdir_detected"
            ].to_numpy(
                dtype=bool
            )
        )
    )


    ai_pd = (
        _percentage(
            active_fault[
                "ai_raw_alarm"
            ].to_numpy(
                dtype=bool
            )
        )
    )


    naive_or_pd = (
        _percentage(
            active_fault[
                "naive_or_alarm"
            ].to_numpy(
                dtype=bool
            )
        )
    )


    hybrid_pd = (
        _percentage(
            active_fault[
                "hybrid_alarm"
            ].to_numpy(
                dtype=bool
            )
        )
    )


    # ========================================================
    # Episode diagnostics
    # ========================================================

    fdir_episode = (
        _fault_episode_diagnostics(
            dataframe=
                fault_sequence,

            alarm_column=
                "fdir_detected",

            fault_start_min=
                generated[
                    "fault_start_min"
                ],

            fault_end_min=
                generated[
                    "fault_end_min"
                ]
        )
    )


    ai_episode = (
        _fault_episode_diagnostics(
            dataframe=
                fault_sequence,

            alarm_column=
                "ai_raw_alarm",

            fault_start_min=
                generated[
                    "fault_start_min"
                ],

            fault_end_min=
                generated[
                    "fault_end_min"
                ]
        )
    )


    hybrid_episode = (
        _fault_episode_diagnostics(
            dataframe=
                fault_sequence,

            alarm_column=
                "hybrid_alarm",

            fault_start_min=
                generated[
                    "fault_start_min"
                ],

            fault_end_min=
                generated[
                    "fault_end_min"
                ]
        )
    )


    # ========================================================
    # Final scenario result
    # ========================================================

    result = {
        "scenario_id":
            str(
                scenario[
                    "scenario_id"
                ]
            ),

        "scenario_index":
            int(
                scenario[
                    "scenario_index"
                ]
            ),

        "scenario_seed":
            int(
                scenario[
                    "scenario_seed"
                ]
            ),

        "time_sync_error_s":
            float(
                generated[
                    "synchronization_error"
                ]
            ),

        "sequence_failed_epochs":
            int(
                generated[
                    "failed_epochs"
                ]
            ),

        "paired_sequences_complete":
            bool(
                generated[
                    "pairs_complete"
                ]
            ),

        "nominal_valid_epochs":
            int(
                len(
                    nominal
                )
            ),

        "fault_valid_epochs":
            int(
                len(
                    active_fault
                )
            ),

        # ----------------------------------------------------
        # PFA
        # ----------------------------------------------------

        "fdir_pfa":
            fdir_pfa,

        "temporal_ai_pfa":
            ai_pfa,

        "naive_or_pfa":
            naive_or_pfa,

        "hybrid_pfa":
            hybrid_pfa,

        # ----------------------------------------------------
        # PD
        # ----------------------------------------------------

        "fdir_pd":
            fdir_pd,

        "temporal_ai_pd":
            ai_pd,

        "naive_or_pd":
            naive_or_pd,

        "hybrid_pd":
            hybrid_pd,

        "hybrid_minus_fdir_pd":
            (
                hybrid_pd
                -
                fdir_pd
            ),

        "temporal_minus_fdir_pd":
            (
                ai_pd
                -
                fdir_pd
            ),

        # ----------------------------------------------------
        # Nominal nuisance episodes
        # ----------------------------------------------------

        "fdir_false_alarm_episodes":
            _count_alarm_episodes(
                nominal,
                "fdir_detected"
            ),

        "temporal_ai_false_alarm_episodes":
            _count_alarm_episodes(
                nominal,
                "ai_raw_alarm"
            ),

        "naive_or_false_alarm_episodes":
            _count_alarm_episodes(
                nominal,
                "naive_or_alarm"
            ),

        "hybrid_false_alarm_episodes":
            _count_alarm_episodes(
                nominal,
                "hybrid_alarm"
            ),

        # ----------------------------------------------------
        # Episode detection
        # ----------------------------------------------------

        "fdir_episode_detected":
            int(
                fdir_episode[
                    "episode_detected"
                ]
            ),

        "temporal_ai_episode_detected":
            int(
                ai_episode[
                    "episode_detected"
                ]
            ),

        "hybrid_episode_detected":
            int(
                hybrid_episode[
                    "episode_detected"
                ]
            ),

        "fdir_preexisting_alarm":
            int(
                fdir_episode[
                    "preexisting_alarm"
                ]
            ),

        "temporal_ai_preexisting_alarm":
            int(
                ai_episode[
                    "preexisting_alarm"
                ]
            ),

        "hybrid_preexisting_alarm":
            int(
                hybrid_episode[
                    "preexisting_alarm"
                ]
            ),

        "fdir_latency_s":
            fdir_episode[
                "latency_s"
            ],

        "temporal_ai_latency_s":
            ai_episode[
                "latency_s"
            ],

        "hybrid_latency_s":
            hybrid_episode[
                "latency_s"
            ],

        # ----------------------------------------------------
        # AI score diagnostics
        # ----------------------------------------------------

        "nominal_mean_ai_score":
            float(
                np.mean(
                    nominal[
                        "temporal_score"
                    ]
                )
            ),

        "fault_mean_ai_score":
            float(
                np.mean(
                    active_fault[
                        "temporal_score"
                    ]
                )
            )
    }


    return result